### ISSUE TITLE
Force closed

### ISSUE THREAD

**Issue by davidohayon669** [MutinyWallet/mutiny-web#719] opened 2023-11-16 22:11 UTC
why did this happened?

![image](https://github.com/MutinyWallet/mutiny-web/assets/7001025/80c48699-1cdd-470d-89ba-fb69a689bc72)

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13384559/mutiny-logs.txt)

also, the [closing tx](https://mempool.space/tx/e971e2f1c51c9fc052a50aa91b1dd932532b0eb27ea862a0bd7aebad134a98a6) seems to be confirmed but i haven't received any funds

**Comment by TonyGiorgio** [comment] 2023-11-16 22:13
This is because you had a pending payment (probably to a zeus user) that did not complete in time and you went offline past the timelock. 

If the closing transaction is confirmed, try resyncing chain in the admin tools in the settings.

**Comment by TonyGiorgio** [comment] 2023-11-16 22:15
Actually, as the indication in the popup: "funds may take a few days to be swept back in the wallet"

**Comment by davidohayon669** [comment] 2023-11-16 22:17
@TonyGiorgio can this be a hodl invoice thing? can you show me in the logs what was the transaction and how did the expiries went wrong? for education

why would on-chain funds take time if they are confirmed?

**Comment by TonyGiorgio** [comment] 2023-11-16 22:19
I'll double check the logs. As far as the on chain funds go, there's a 2nd transaction that has to occur but it has to occur after the timelock on the first. Which can vary to being 24 - 36 hours or so typically.

**Comment by davidohayon669** [comment] 2023-11-16 22:24
@TonyGiorgio i should have opened the app every day to mitigate this?

**Comment by TonyGiorgio** [comment] 2023-11-16 22:27
```
af48 2023-11-16 21:10:54.628 TRACE [lightning::chain::channelmonitor:3567] Processing 0 matched transactions for block at height 817072.
af48 2023-11-16 21:10:54.628 INFO  [lightning::chain::channelmonitor:3865] Force-closing channel due to outbound HTLC timeout, HTLC expiry is 816437
```

I couldn't find the exact invoice this occured from. But you last opened the wallet on Nov 11th when those payments went out. We made an update two days ago that stopped sending payments to Zeus hold invoices by default. So it should happen a lot less frequently. It is wise to open the wallet every few days at least, but when there's a pending payment, it is very important to open the wallet every day until it completes or fails.

**Comment by davidohayon669** [comment] 2023-11-16 22:41
@TonyGiorgio got you... thanks

**Comment by TonyGiorgio** [comment] 2023-11-16 22:45
No problem, sorry about that. If the funds do not return when you check the wallet tomorrow or the next day, let us know and we can reopen this issue.

**Closed by TonyGiorgio** 2023-11-16 22:45 UTC
