### ISSUE TITLE
NOSTR contacts not resyncing

### ISSUE THREAD

**Issue by JarrydVanHoy** [MutinyWallet/mutiny-web#840] opened 2024-01-20 20:41 UTC
Regardless if I resync or remove then readd my npub, my NOSTR contacts don't seem to sync up properly.  For example, I know one of my contacts has updated their LN address and have validated multiple times by looking at their profile and with them via chat, but it does not reflect their new LN address on Mutiny.

**Comment by benthecarman** [comment] 2024-01-20 20:44
Can you share his npub and your own?

**Comment by JarrydVanHoy** [comment] 2024-01-20 20:48
Mine: npub1wll0qynj8m5g4s4qlq48wdg6t8t7vqmn9mtznr4zglxpfjj0l03q4nm50t
Friend's: npub174cnrmyaw58srerln3r3nk4a8774r0hudf6678lfnulck2g9hq7sm04h5a

Friend's new LN address: andmich@strike.me
What I see on Mutiny for him: uglyoil40@walletofsatoshi.com

**Comment by benthecarman** [comment] 2024-01-20 21:18
I can reproduce the issue, looks like our caching service has not picked up your friend's latest profile update, will work on resolving.

In the mean time you can edit his contact from the activity screen to change his lightning address to the expect value.

**Comment by TonyGiorgio** [comment] 2024-01-20 21:21
Nostr has no final global state, so these things are bound to happen and they do happen. Hopefullly it updates more generally everywhere but for now you can update.

**Closed by TonyGiorgio** 2024-01-20 21:21 UTC

**Comment by JarrydVanHoy** [comment] 2024-01-20 21:35
Yeah I get that but it's been weeks.  Does it normally take that long or is there a way to hard refresh because the contacts stay even after removing my npub?

**Comment by benthecarman** [comment] 2024-04-02 22:13
I think if your friend just updates his profile again it'll fix the issue. Sadly I'm not sure if there's a way to force the primal cache to resync a profile. If he updates his profile it should force it to resync.

**Comment by JarrydVanHoy** [comment] 2024-04-03 01:40
@benthecarman that seems to have fixed it.  He removed it, saved the changes, then readded it back and saved the changes.

Thanks for the suggestion.
