### ISSUE TITLE
Closed lightning channel, where does the sats go?

### ISSUE THREAD

**Issue by andysavage** [MutinyWallet/mutiny-web#1298] opened 2024-09-07 14:46 UTC
Hi I closed the lightning channel and waited to see the sats back in my on-chain wallet, but now there is no sign of them anywhere. How can I see where they should go? Would they go to the original wallet I sent in funds from or does mutiny have its own onchain wallet, cos I cannot see one. Balance is entirely zero
Thanks

![mutiny1](https://github.com/user-attachments/assets/6d3c931b-819a-4002-a54a-418c84e72008)
![mutiny2](https://github.com/user-attachments/assets/a61fd917-dd98-4db2-a778-85ae059cb0b5)

**Comment by marksftw** [comment] 2024-09-12 00:48
You can try loading it into Sparrow with your 12 word seed phrase. Be sure to use the derivation path at this link: https://github.com/MutinyWallet/mutiny-web/wiki/Recovery?ref=blog.mutinywallet.com#on-chain

**Comment by andysavage** [comment] 2024-09-12 13:04
Hi thanks for replying. I tried this but it gives an empty wallet. Also I dont understand the stuff about derivation path, I tried pasting in m/86'/0'/0' as in the link you gave but this it says is invald so I am misunderstanding something. I was unable to find anything relevant that I could copy from the mutuny site either, apart from the 12 word passphrase.

**Comment by andysavage** [comment] 2024-09-12 13:05
> You can try loading it into Sparrow with your 12 word seed phrase. Be sure to use the derivation path at this link: https://github.com/MutinyWallet/mutiny-web/wiki/Recovery?ref=blog.mutinywallet.com#on-chain

Hi thanks for replying. I tried this but it gives an empty wallet. Also I dont understand the stuff about derivation path, I tried pasting in m/86'/0'/0' as in the link you gave but this it says is invald so I am misunderstanding something. I was unable to find anything relevant that I could copy from the mutuny site either, apart from the 12 word passphrase.

This is very different to what I'm used to!

**Comment by stasgnikcats** [comment] 2024-10-08 17:20
I have this same issue from 9-25-2024. I closed a channel (I think it was with Zeus). Funds not showing. As the user above noted, Sparrow does not allow you to generate a wallet with custom derivation path m/86'/0'/0'. Here are my [logs]([mutiny-logs.txt](https://github.com/user-attachments/files/17296966/mutiny-logs.txt)) which don't go back to the 25th unfortunately so I figure they will not be worth anything. The channel close note reads as if the LSP performed a justice transaction due to non consensus of fee: 
![IMG_3067](https://github.com/user-attachments/assets/91f00d39-5c7e-43f0-b8c9-9dd7cb29628b)

**Comment by DanConwayDev** [comment] 2024-10-16 07:58
@andysavage  that's the taproot derivation path. I also found that I couldn't manually enter the derivation path with sparrow but it loads that derivation you select taproot under script type. 
Unfortunately like @stasgnikcats, I cannot find the output of the force close transaction under that derivation. I set the gap limit to 200 to no avail.

**Comment by DanConwayDev** [comment] 2024-10-16 08:15
I've heard that the standard derivation path is not used for forced channels. Its calcuated based on your channel state. apparently LDK has some recovery tools if you still have your channel state (you can export this under Emergency Kit) and maybe your seed words. I'll investigate later and report back.

**Comment by andysavage** [comment] 2024-10-16 18:58
Thanks, I have the seed phrase and I downloaded the state. I lost browser history etc and the logs only go back about 2 weeks when I re-entered my seed into the website to see if I could empty it.

**Comment by stasgnikcats** [comment] 2024-10-17 17:44
@DanConwayDev thanks for looking into this. I was able to locate the 86 TR derivation path transactions and pinpoint the force close transaction. To me, it seems like Mutiny did not have a matching fee rate to Zeus. It appears to be around half (2 sats/vB) of what Zeus was using for their consensus (4 sats/vB). In this case, Zeus initiated a justice transaction and just stole my funds. The bitcoin has subsequently been combined with other UTXOs and transferred multiple times since I demanded a close on 9/25. This is the address of the force close tx: https://mempool.space/address/bc1pujytq58vctrajxg2r2uczgy6ttgkdgfy8xy5grmpfftr5vu8xlzq7mrp6y

Short of trying to work with Zeus directly, I'm not sure if there is anything else I can do to get my funds back. I have a feeling this will cause further issues for others who are being instructed to close channels as Mutiny sunsets....

**Comment by stasgnikcats** [comment] 2024-10-26 23:38
*Update*: I was able to troubleshoot with Zeus and I am squared away. Thanks for taking a look!

OP still may not have been rectified...

**Closed as completed** 2024-12-30 19:52 UTC

**Comment by andysavage** [comment] 2025-01-09 00:56
Ok I give up. I'll put it down to experience and be more careful what I use in future. 
Still I think "completed" is not the most approriate epitaph for the issue!

All the best.

**Comment by DanConwayDev** [comment] 2025-01-09 09:19
@andysavage I think what happened to you is what happened to me also. The channel close transaction has a 1sat/vb fee rate and Mutiny Wallet doesnt show it until its confirmed. unfortunately the utxo from the close transaction is not on the standard taproot derivation path but calculated based on the state. I can't send to the standard taproot derivation via CPFP because Mutinty doesn't show it in the interface.

I found my close transaction and can see it in the mempool. I considered shelling out $50 to bump the transaction via mempool.space accelerator. I spoke to Voltage who said they may look at fee bumping at their end. After all, they have funds locked up too.

This didnt quite happen by the end of the year so I regret not doing it as Mutinty have turned off their infrastructure so the App doesnt work.

If Voltage aren't in a position to take all the funds (as I can no longer issue a justice transaction) and send me my share, I'll have to work out how to stand up the self-hosted infrastructure when Voltage get around it to doing their bit.

Hopefully the unmaintained self-hosted infrascture software will still work at that point.

If it happens, I'll let you know. I could even let you the infrastructure I stand up, so that you can find your close transaction and get it resolved.

**Comment by andysavage** [comment] 2025-01-09 20:15
> @andysavage I think what happened to you is what happened to me also. The 
> If it happens, I'll let you know. I could even let you the infrastructure I stand up, so that you can find your close transaction and get it resolved.

Thanks, but I think the whole thing is beyond my understanding! I don't remember how much was in there but it's not a lot. I'll put it down to experience and focus on our BTCPay node, and learn all I can about that. I've been using coinos.io for day-to-day transactions and they have been very good. They even opened a channel to paxful when I told them I was having trouble sending there. 

All the best and good luck,
Andy
