### ISSUE TITLE
On-chain funds stuck, possibly related to fee bump

### ISSUE THREAD

**Issue by CidadaoB** [MutinyWallet/mutiny-web#531] opened 2023-09-14 14:17 UTC
Description:
I am experiencing an issue similar to [this one](https://github.com/MutinyWallet/mutiny-web/issues/340). My funds have not appeared in my wallet after closing two channels four days ago.

Channel IDs:
67e180469571abd56d15d106e06a05486772da8eff96699138015d9d737609ad
5f88fe3ae2512ba05e7d71d1d733b8da0588415aac4fd5dc32e2e96f7662a20e

Steps to Reproduce:
Sent 1.45M sats to my wallet.
Attempted to convert UTXO to Lightning with a 7 sats/vByte fee.
Transaction was stuck for 2-3 weeks.
Imported wallet into Sparrow Wallet and bumped the fee,  [transaction got processed](https://mempool.space/tx/87ec7dfb1b3e4879d595c2a0e2fe3649aadd6478ed41030f75d827d78a217ab5)

Channels displayed confirmations: 0 even after several hours.
Decided to close both channels which showed 0 confirmations.

Expected Behavior:
Funds should have returned to my wallet after closing the channels.

Actual Behavior:
Funds have not appeared in my wallet after four days.

If i open up the console when stating mutiny i can see its trying to broadcast both transactions for the channel closes (i suppose) and its failing. Also appears in the logs.

Attaching logs: [mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12609891/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment] 2023-09-14 15:08
You should absolutely not be bumping the fee on a channel open externally. I highly doubt this will be recoverable at all. Does the channels show up in your wallet at all? In the admin tools? I doubt it. It considers your channel as closed because you respent it.

**Comment by CidadaoB** [comment] 2023-09-14 15:44
> You should absolutely not be bumping the fee on a channel open externally. I highly doubt this will be recoverable at all. Does the channels show up in your wallet at all? In the admin tools? I doubt it. It considers your channel as closed because you respent it.

This is how it appears:

![image](https://github.com/MutinyWallet/mutiny-web/assets/16735558/49029ff9-3c1c-4ecc-b9e3-8d0cdcd9936f)

In the admin tools channels don't appear because i closed them, i couldnt spend my sats before closing either thought, I notice that everytime i load the wallet it tries to broadcast this transactions but fails:

![image](https://github.com/MutinyWallet/mutiny-web/assets/16735558/5ade6def-3138-4a8d-af32-a526bad5319a)


payloads seeem like incomplete transactions which can be pasted in sparrow:

0200000000010167e180469571abd56d15d106e06a05486772da8eff96699138015d9d737609ad0000000000337a7e80014130160000000000220020a5e0eae62c751f3d6aa6f91ae99fbae9ffac0def2184d10cd5fb4b646afd36140400473044022075c42ae1cb610b4f6eb62c2dd8972dabdb483800335140521fbdcca751655ed802206dadd3c38e816ca0c4dfb74b5edefa87b78662db38f535b893a729a4f52b364c0147304402206410a0755c7c5c8f07a789d2802379ad0a3010995ef7c27965ed9f5b1893434802205cb1e138346c832e14cbe1ae9b9037e11b6963e0919bf200919997445eecdf4001475221023d86e85e2ad3d431ac6fc57fc120f78cfd015701d284dc9adbe56aa5cdee6bef2102612e2ea1a1067e4f584b3c1630bb5c7e06024cd27739721c6645365df4e7182552ae9db0cf20

And

020000000001015f88fe3ae2512ba05e7d71d1d733b8da0588415aac4fd5dc32e2e96f7662a20f0100000000eab7d380025704000000000000220020636500cd4ef1562c86bf78efa3843dd059acf99362acc274ddbe5c7520be79b0dfbd1000000000001600143c8e46ea3e9722333b9c6b6fd1975e4a4a28b4ce04004730440220505e0495188265675fd1ad894735b7c7b2a4cc9cf373fde26296d6c8659013a8022007d771441e0c436f32b9ddefabbf15be02a4f73bcfb4be6a7332441c76bcfc580147304402202c58562bd5cdc553c44dd43b3c9bc32abe338cee02ab7d55b9514c56d991f4b40220581797221cb3266e862509e6a7429015a2635d5cf6a2f11e81d5332cb060f6fa01475221029cf10cd02cbcd8be2b19a6713063f78ab09d98c5d0ec1a57f665de971e09a36b2102a221b0b6fa9027475ae9603ecf0e16b9ea58987319d3a139eaef55d4b27ead0b52aeb4e0d320

So if i cant bump the fee when opening a channel, what am i to do? wait for every for the mempool to clear? what if it never clears?

**Comment by CidadaoB** [comment] 2023-09-14 15:54
> > So if i cant bump the fee when opening a channel, what am i to do? wait for every for the mempool to clear? what if it never clears?
> 
> I get that it's not obvious and we don't have anything in app to support fee bumps. But just to double check, when you did the fee bump, did you spend it to the same outputs? That would have been the problem. Lightning nodes don't lilke it when you change the transaction ID of a channel opening especially when it changes out of band. From the perspective of your node and the other counterparty, your channel funding transaction doesn't exist and is locked in a 2 of 2 that requires a force close on one side but neither side is aware of it.
> 
> I'll bring this up with some lightning protocol devs but honestly I don't know what we can do here.

Yes, i spent it to the same outputs, the original tx was https://mempool.space/tx/ad0976739d5d0138916996ff8eda726748056ae006d1156dd5ab71954680e167
I guess the lightning node is waiting for that transaction.

It's not appearing as rbf'd anymore for some reason, but yeah all i did was up the fee with sparrow sending to the same address.

**Comment by TonyGiorgio** [comment] 2023-09-14 15:56
> It's not appearing as rbf'd anymore for some reason, but yeah all i did was up the fee with sparrow sending to the same address.

It's confirmed so yeah the original would not be able to be confirmed nor changed anymore. What's your node id? It's in the admin tool settings at the top. I'll see if anything appears on the LSP side.

**Comment by TonyGiorgio** [comment] 2023-09-14 16:29
Did you have two channels and did the same on both? Or is one of the channels the original and one of them is a fee bump?

**Comment by CidadaoB** [comment] 2023-09-14 16:48
hmm, so what i remember is that i had 3 channels, 2 of them where giving the trouble, i closed all 3.

The one which was ok closed fine, it had hundreds or thousands of confirmations and returned a 514 sats utxo to me.

The other 2 had 0 confirmations for many hours, its the ones i put the id of in the OP

**Comment by TonyGiorgio** [comment] 2023-09-14 16:55
I'm confused here. Was it the closing of the channels that you fee bumped or was it the opening of the channels that you fee bumped?

**Comment by CidadaoB** [comment] 2023-09-14 17:15
> I'm confused here. Was it the closing of the channels that you fee bumped or was it the opening of the channels that you fee bumped?

Sorry,

Its the opening what i fee bumped.

I had been using Mutiny for a few days without problems, so i guess that i had 1 channel opened.

After that i tried to load deposit more btc, so i deposited, that channel opening got stuck at 7 sats/vb, i bumped it. I guess that this created 2 new channels which showed 0 confirmations all the time, i clicked close channels and it got stuck there.

**Comment by TonyGiorgio** [comment] 2023-09-14 17:34
So this is what is shown on the LSP side: 

```
{
   "closedchannels": [
      {
         "peer_id": "02fb625fbe516b499c2b35fc81b3d955da763c9c8b38d34b6ce696c255dfbf06de",
         "channel_id": "1911b9fe7257c92375db2f8f8f04c44955ccf348356967144bfbb8a307668ed7",
         "short_channel_id": "805360x1451x0",
         "alias": {
            "local": "9258955x6219329x65097",
            "remote": "587440x2246x1"
         },
         "opener": "local",
         "closer": "remote",
         "private": true,
         "channel_type": {
            "bits": [
               12,
               46
            ],
            "names": [
               "static_remotekey/even",
               "scid_alias/even"
            ]
         },
         "total_local_commitments": 35,
         "total_remote_commitments": 35,
         "total_htlcs_sent": 1,
         "funding_txid": "d78e6607a3b8fb4b1467693548f3cc5549c4048f8f2fdb7523c95772feb91119",
         "funding_outnum": 0,
         "leased": false,
         "total_msat": 191920000,
         "final_to_us_msat": 191373796,
         "min_to_us_msat": 101920000,
         "max_to_us_msat": 191920000,
         "last_commitment_txid": "120715b3cbfab80abcff7ab54edd40e9725acc5d9ee6296e8b70c7a80ad71123",
         "last_commitment_fee_msat": 191374000,
         "close_cause": "remote"
      },
      {
         "peer_id": "02fb625fbe516b499c2b35fc81b3d955da763c9c8b38d34b6ce696c255dfbf06de",
         "channel_id": "67e180469571abd56d15d106e06a05486772da8eff96699138015d9d737609ad",
         "alias": {
            "local": "14395038x2175344x26598"
         },
         "opener": "remote",
         "closer": "remote",
         "private": true,
         "channel_type": {
            "bits": [
               12,
               46
            ],
            "names": [
               "static_remotekey/even",
               "scid_alias/even"
            ]
         },
         "total_local_commitments": 0,
         "total_remote_commitments": 0,
         "total_htlcs_sent": 0,
         "funding_txid": "ad0976739d5d0138916996ff8eda726748056ae006d1156dd5ab71954680e167",
         "funding_outnum": 0,
         "leased": false,
         "total_msat": 1455412000,
         "final_to_us_msat": 0,
         "min_to_us_msat": 0,
         "max_to_us_msat": 0,
         "last_commitment_txid": "54a04e96339f6c01858f05b13dc6a3b7b65d5c76291c56662afe257008e50cc7",
         "last_commitment_fee_msat": 1769000,
         "close_cause": "remote"
      }
   ]
}
```

```
      {
         "peer_id": "02fb625fbe516b499c2b35fc81b3d955da763c9c8b38d34b6ce696c255dfbf06de",
         "connected": false,
         "state": "CLOSINGD_COMPLETE",
         "channel_id": "5f88fe3ae2512ba05e7d71d1d733b8da0588415aac4fd5dc32e2e96f7662a20e",
         "our_amount_msat": 1099899471,
         "amount_msat": 1101011000,
         "funding_txid": "0fa262766fe9e232dcd54fac5a418805dab833d7d1717d5ea02b51e23afe885f",
         "funding_output": 1
      },
```

If I'm following all of your info correctly, I don't see the fee bumped channel open here so the other node is unaware of that channel. I have talked to someone on the LDK side and it's not looking good. I'll see if there's anything on the CLN side that can be done but essentially you double spent a channel open to a 2 of 2 address that none of these nodes understand, across two different node implementations. I wouldn't hold my breath unfortunately.

**Comment by TonyGiorgio** [comment] 2023-09-14 17:51
I've opened up an issue on the CLN side. Assuming there's a way for that node to do it, we can investigate how much work we need to do to build a tool for you to recover these funds. If there's nothing on the CLN side for doing this, then there's nothing we can do on the mutiny wallet side since it needs cooperation from both parties. https://github.com/ElementsProject/lightning/issues/6681

**Comment by CidadaoB** [comment] 2023-09-14 18:49
I see, thanks a lot for the help and trying, i think you nailed it on the https://github.com/ElementsProject/lightning/issues/6681 ticket. My bad after all, should've opened a ticked before manually bumping the fee

**Closed** 2023-11-04 22:20 UTC
Labels: wontfix
