### ISSUE TITLE
Pending transaction and the and then a channel close

### ISSUE THREAD

**Issue by mariaa144** [MutinyWallet/mutiny-web#803] opened 2024-01-07 16:55 UTC
This type of thing happens to me a lot. So far about 5 or 6 times since using Mutiny. I am happily Zapping away on Amethyst and then at least on transaction will get stuck in "Pending". The last time I noticed the invoice had expired, when I tried to pay it from Zeus. Then, a few days later I will see a channel close which is quite expensive.

How can I prevent this from happening? I would really like my channel to not close.

I am using Mutiny APK on GraphineOS. I think I'm up-to-date at version 0.5.1. VersionCode 43.

**Comment by TonyGiorgio** [comment] 2024-01-07 17:05
Open the wallet more often if you know you have a pending transaction.

**Comment by mariaa144** [comment] 2024-01-07 18:53
I see. I thought I opened Mutiny right away once I zapped.

I would very much like to keep Muntiny on in the background all the time but it often closes when I switch apps.

**Comment by TonyGiorgio** [comment] 2024-01-09 01:15
> I thought I opened Mutiny right away once I zapped.

The problem is that it might still be pending while the zapping is happening. If you open it, it'll initiate the zaps. If you closed it immediately after, you'll have a pending payment stuck, and if you don't open it again for a few days, it'll cause you to have a force closed channel. 

Probably depends on the OS and Phone, but it does stay kind of backgrounded for a little bit, but that's phone policies at play.

**Closed by TonyGiorgio** 2024-01-09 01:15 UTC
